{
  'hosts':{'gloria':{'username':"USERNAME",
                     'password':"PASSWORD"},
           'melman':{'username':"USERNAME",
                     'password':"PASSWORD"},
           'kowalski':{'username':"USERNAME",
                     'password':"PASSWORD"},},
  'features_keys':['_id','mean','amplitude',
            'period_ELS','significance_ELS',
            'period_ECE','significance_ECE',
            'period_EAOV','significance_EAOV',
            'period_ELS_ECE_EAOV','significance_ELS_ECE_EAOV',
            'AllWISE___id','AllWISE__w1mpro',
            'AllWISE__w1sigmpro','AllWISE__w2mpro',
            'AllWISE__w2sigmpro','AllWISE__w3mpro',
            'AllWISE__w3sigmpro','AllWISE__w4mpro',
            'AllWISE__w4sigmpro','AllWISE__ph_qual',
            'Gaia_EDR3___id','Gaia_EDR3__phot_g_mean_mag',
            'Gaia_EDR3__phot_bp_mean_mag','Gaia_EDR3__phot_rp_mean_mag',
            'Gaia_EDR3__parallax','Gaia_EDR3__parallax_error',
            'Gaia_EDR3__pmra','Gaia_EDR3__pmra_error','Gaia_EDR3__pmdec',
            'Gaia_EDR3__pmdec_error','Gaia_EDR3__astrometric_excess_noise',
            'Gaia_EDR3__phot_bp_rp_excess_factor',
            'PS1_DR1___id','PS1_DR1__gMeanPSFMag',
            'PS1_DR1__gMeanPSFMagErr','PS1_DR1__rMeanPSFMag',
            'PS1_DR1__rMeanPSFMagErr','PS1_DR1__iMeanPSFMag',
            'PS1_DR1__iMeanPSFMagErr','PS1_DR1__zMeanPSFMag',
            'PS1_DR1__zMeanPSFMagErr','PS1_DR1__yMeanPSFMag',
            'PS1_DR1__yMeanPSFMagErr','PS1_DR1__qualityFlag',],
    'classification_keys':['_id',
            'ra','dec',
            'period',
            'field',
            'ccd',
            'quad',
            'filter',
            'e_dnn','dscu_dnn','dp_dnn','mir_dnn','rrc_dnn','agn_dnn','puls_dnn',
            'bogus_dnn','rscvn_dnn','wvir_dnn','lpv_dnn','rrlyr_dnn','rrd_dnn','emsms_dnn',
            'mp_dnn','ew_dnn','bis_dnn','blher_dnn','srv_dnn','fla_dnn','i_dnn','ceph2_dnn',
            'ea_dnn','wuma_dnn','rrblz_dnn','ceph_dnn','osarg_dnn','ext_dnn','bright_dnn',
            'el_dnn','dip_dnn','vnv_dnn','cv_dnn','pnp_dnn','sin_dnn','blend_dnn','eb_dnn',
            'wp_dnn','rrab_dnn','hp_dnn','blyr_dnn','saw_dnn','longt_dnn','yso_dnn','blend_xgb',
            'hp_xgb','bis_xgb','wp_xgb','eb_xgb','ceph_xgb','bright_xgb','wuma_xgb','longt_xgb',
            'rrd_xgb','ceph2_xgb','osarg_xgb','rrblz_xgb','blyr_xgb','ea_xgb','lpv_xgb','agn_xgb',
            'el_xgb','e_xgb','rrab_xgb','cv_xgb','mir_xgb','rrc_xgb','mp_xgb','yso_xgb','wvir_xgb',
            'saw_xgb','puls_xgb','ew_xgb','sin_xgb','blher_xgb','dscu_xgb','dp_xgb','vnv_xgb','pnp_xgb',
            'bogus_xgb','dip_xgb','i_xgb','rscvn_xgb','ext_xgb','emsms_xgb','srv_xgb','rrlyr_xgb','fla_xgb']
}